# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/DataPath_more_0/DataPath_more_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_more_0 || ORIG_REF_NAME==DataPath_more_0} -quiet] -quiet

# IP: ip/DataPath_more_0/ip/RV_Int_0/RV_Int_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RV_Int_0 || ORIG_REF_NAME==RV_Int_0} -quiet] -quiet

# IP: ip/DataPath_more_0/ip/REG32_0/REG32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==REG32_0 || ORIG_REF_NAME==REG32_0} -quiet] -quiet

# IP: ip/DataPath_more_0/ip/ALU_0_1/ALU_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_0 || ORIG_REF_NAME==ALU_0} -quiet] -quiet

# IP: ip/DataPath_more_0/ip/Regs_0/Regs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Regs_0 || ORIG_REF_NAME==Regs_0} -quiet] -quiet

# IP: ip/DataPath_more_0/ip/MUX2T1_32_0/MUX2T1_32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX2T1_32_0 || ORIG_REF_NAME==MUX2T1_32_0} -quiet] -quiet

# IP: ip/DataPath_more_0/ip/MUX4T1_32_1/MUX4T1_32_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX4T1_32_1 || ORIG_REF_NAME==MUX4T1_32_1} -quiet] -quiet

# IP: ip/DataPath_more_0/ip/MUX4T1_32_0/MUX4T1_32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX4T1_32_0 || ORIG_REF_NAME==MUX4T1_32_0} -quiet] -quiet

# IP: ip/DataPath_more_0/ip/MUX2T1_32_1/MUX2T1_32_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX2T1_32_1 || ORIG_REF_NAME==MUX2T1_32_1} -quiet] -quiet

# IP: ip/DataPath_more_0/ip/add_32_1/add_32_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_32_1 || ORIG_REF_NAME==add_32_1} -quiet] -quiet

# IP: ip/DataPath_more_0/ip/add_32_0/add_32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_32_0 || ORIG_REF_NAME==add_32_0} -quiet] -quiet

# IP: ip/DataPath_more_0/ip/ImmGen_0/ImmGen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ImmGen_0 || ORIG_REF_NAME==ImmGen_0} -quiet] -quiet
