# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/Pipeline_Soc/SOC/SOC.cache/wt} [current_project]
set_property parent.project_path {C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/Pipeline_Soc/SOC/SOC.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{c:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/IP}} [current_project]
set_property ip_output_repo {c:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/Pipeline_Soc/SOC/SOC.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/D_mem.coe}}
add_files {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/P.coe}}
add_files {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/h_new.coe}}
read_verilog -library xil_defaultlib {
  {C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/IP/Counter_x.v}
  {C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/IP/MIO_BUS.v}
  {C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/IP/Multi_8CH32.v}
  {C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/IP/SAnti_jitter.v}
  {C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/IP/SPIO.v}
  {C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/IP/clk_div.v}
  {C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/Pipeline_Soc/SOC/SOC.srcs/sources_1/new/CSSTE.v}
}
read_ip -quiet {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/Pipeline_Soc/SOC/SOC.srcs/sources_1/ip/VGA_0/VGA_0.xci}}

read_ip -quiet {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/Pipeline_Soc/SOC/SOC.srcs/sources_1/ip/SSeg7_Dev_0/SSeg7_Dev_0.xci}}

read_ip -quiet {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/Pipeline_Soc/SOC/SOC.srcs/sources_1/ip/RAM_B/RAM_B.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/Pipeline_Soc/SOC/SOC.srcs/sources_1/ip/RAM_B/RAM_B_ooc.xdc}}]

read_ip -quiet {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/Pipeline_Soc/SOC/SOC.srcs/sources_1/ip/ROM_D/ROM_D.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/Pipeline_Soc/SOC/SOC.srcs/sources_1/ip/ROM_D/ROM_D_ooc.xdc}}]

read_ip -quiet {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/Pipeline_Soc/SOC/SOC.srcs/sources_1/ip/Pipeline_CPU_0/Pipeline_CPU_0.xci}}

read_edif {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/IP/Counter_x.edf}}
read_edif {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/IP/SAnti_jitter.edf}}
read_edif {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/IP/clk_div.edf}}
read_edif {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/IP/SPIO.edf}}
read_edif {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/IP/Multi_8CH32.edf}}
read_edif {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/IP/MIO_BUS.edf}}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/Org-Sword.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/Org-Sword.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top CSSTE -part xc7k160tffg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CSSTE.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CSSTE_utilization_synth.rpt -pb CSSTE_utilization_synth.pb"
