# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/lenovo/Desktop/Computer Organization Lab/Lab5/Org-Sword.xdc

# IP: ip/VGA_0/VGA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_0 || ORIG_REF_NAME==VGA_0} -quiet] -quiet

# IP: ip/SSeg7_Dev_0/SSeg7_Dev_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SSeg7_Dev_0 || ORIG_REF_NAME==SSeg7_Dev_0} -quiet] -quiet

# IP: ip/RAM_B/RAM_B.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_B || ORIG_REF_NAME==RAM_B} -quiet] -quiet

# IP: ip/ROM_D/ROM_D.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_D || ORIG_REF_NAME==ROM_D} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/Pipeline_CPU_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pipeline_CPU_0 || ORIG_REF_NAME==Pipeline_CPU_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/stall_0/stall_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stall_0 || ORIG_REF_NAME==stall_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_WB_0/Pipeline_WB_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pipeline_WB_0 || ORIG_REF_NAME==Pipeline_WB_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_WB_0/ip/MUX4T1_32_0/MUX4T1_32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX4T1_32_0 || ORIG_REF_NAME==MUX4T1_32_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Mem_reg_WB_0/Mem_reg_WB_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mem_reg_WB_0 || ORIG_REF_NAME==Mem_reg_WB_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_Mem_0/Pipeline_Mem_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pipeline_Mem_0 || ORIG_REF_NAME==Pipeline_Mem_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Ex_reg_Mem_0/Ex_reg_Mem_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ex_reg_Mem_0 || ORIG_REF_NAME==Ex_reg_Mem_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_Ex_0/Pipeline_Ex_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pipeline_Ex_0 || ORIG_REF_NAME==Pipeline_Ex_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_Ex_0/ip/ALU_0/ALU_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_0 || ORIG_REF_NAME==ALU_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_Ex_0/ip/MUX2T1_32_0/MUX2T1_32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX2T1_32_0 || ORIG_REF_NAME==MUX2T1_32_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_Ex_0/ip/add_32_1/add_32_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_32_1 || ORIG_REF_NAME==add_32_1} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_Ex_0/ip/add_32_0/add_32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_32_0 || ORIG_REF_NAME==add_32_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/ID_reg_Ex_0/ID_reg_Ex_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ID_reg_Ex_0 || ORIG_REF_NAME==ID_reg_Ex_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_ID_0/Pipeline_ID_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pipeline_ID_0 || ORIG_REF_NAME==Pipeline_ID_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_ID_0/ip/SCPU_ctrl_0/SCPU_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SCPU_ctrl_0 || ORIG_REF_NAME==SCPU_ctrl_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_ID_0/ip/ImmGen_0/ImmGen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ImmGen_0 || ORIG_REF_NAME==ImmGen_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_ID_0/ip/Regs_0/Regs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Regs_0 || ORIG_REF_NAME==Regs_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/IF_reg_ID_0/IF_reg_ID_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IF_reg_ID_0 || ORIG_REF_NAME==IF_reg_ID_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_IF_0/Pipeline_IF_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pipeline_IF_0 || ORIG_REF_NAME==Pipeline_IF_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_IF_0/ip/add_32_0/add_32_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_32_0 || ORIG_REF_NAME==add_32_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_IF_0/ip/REG32_0/REG32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==REG32_0 || ORIG_REF_NAME==REG32_0} -quiet] -quiet

# IP: ip/Pipeline_CPU_0/ip/Pipeline_IF_0/ip/MUX2T1_32_0/MUX2T1_32_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX2T1_32_0 || ORIG_REF_NAME==MUX2T1_32_0} -quiet] -quiet

# XDC: ip/RAM_B/RAM_B_ooc.xdc

# XDC: ip/ROM_D/ROM_D_ooc.xdc
